/**
 * The curated commerce catalog — the ONLY pool the recommendation engine picks
 * from. Real, mainstream products with honest approximate prices.
 *
 * Images: `image: require(...)` where a real packshot ships in assets/ (the
 * routine cards bleed these past the card edge); null → the card's quiet
 * brand-tile fallback renders until the packshot is added. Never a vector,
 * never an emoji.
 *
 * Blurbs are PLAIN WORDS (no barrier/sebum/actives/exfoliant jargon — that
 * vocabulary is banned from user-facing copy; internal fields like
 * `activeStrength` never render).
 *
 * Affiliate URLs are Amazon product-intent searches tagged for the affiliate
 * program; the Buy button's backend is swappable (owned checkout later) and
 * reads these as opaque handoff targets.
 */

import type { CommerceSku } from './types';

const amazon = (q: string) =>
  `https://www.amazon.com/s?k=${encodeURIComponent(q)}&tag=puraai-20`;

/**
 * Resolve a packshot's static require. Under Metro the literal require inside
 * the thunk bundles normally (it stays statically analyzable); under Node/tsx
 * (the verifier scripts) requiring a JPEG throws, and we fall back to null —
 * the engine and screens treat that exactly like a SKU without a packshot.
 */
const img = (load: () => number): number | null => {
  try {
    return load();
  } catch {
    return null;
  }
};

export const COMMERCE_CATALOG: readonly CommerceSku[] = [
  // ── CLEANSE ──────────────────────────────────────────────────────────────
  {
    id: 'cerave-hydrating-cleanser',
    brand: 'CeraVe',
    name: 'Hydrating Facial Cleanser',
    step: 'cleanse',
    time: 'both',
    priceTier: 'budget',
    priceUsd: 16,
    concerns: ['dryness', 'sensitive', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('CeraVe Hydrating Facial Cleanser'),
    image: img(() => require('../../assets/products/cerave-hydrating-cleanser.jpg')),
    blurb: 'A soft, creamy wash that cleans without leaving skin tight.',
  },
  {
    id: 'cerave-foaming-cleanser',
    brand: 'CeraVe',
    name: 'Foaming Facial Cleanser',
    step: 'cleanse',
    time: 'both',
    priceTier: 'budget',
    priceUsd: 16,
    concerns: ['oil', 'breakouts', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('CeraVe Foaming Facial Cleanser'),
    image: null,
    blurb: 'A fresh gel wash for skin that gets shiny by midday.',
  },
  {
    id: 'vanicream-gentle-cleanser',
    brand: 'Vanicream',
    name: 'Gentle Facial Cleanser',
    step: 'cleanse',
    time: 'both',
    priceTier: 'budget',
    priceUsd: 12,
    concerns: ['sensitive', 'redness', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Vanicream Gentle Facial Cleanser'),
    image: null,
    blurb: 'About as plain and kind as a face wash gets.',
  },
  {
    id: 'cetaphil-gentle-cleanser',
    brand: 'Cetaphil',
    name: 'Gentle Skin Cleanser',
    step: 'cleanse',
    time: 'both',
    priceTier: 'budget',
    priceUsd: 13,
    concerns: ['sensitive', 'dryness', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Cetaphil Gentle Skin Cleanser'),
    image: null,
    blurb: 'The classic no-drama cleanser dermatologists hand to everyone.',
  },
  {
    id: 'lrp-toleriane-cleanser',
    brand: 'La Roche-Posay',
    name: 'Toleriane Hydrating Gentle Cleanser',
    step: 'cleanse',
    time: 'both',
    priceTier: 'mid',
    priceUsd: 17,
    concerns: ['sensitive', 'redness', 'dryness'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('La Roche-Posay Toleriane Hydrating Gentle Cleanser'),
    image: img(() => require('../../assets/products/la-roche-posay-toleriane-cleanser.jpg')),
    blurb: 'A milky wash made for skin that flushes easily.',
  },
  {
    id: 'lrp-effaclar-cleanser',
    brand: 'La Roche-Posay',
    name: 'Effaclar Purifying Foaming Gel',
    step: 'cleanse',
    time: 'both',
    priceTier: 'mid',
    priceUsd: 17,
    concerns: ['oil', 'breakouts'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('La Roche-Posay Effaclar Purifying Foaming Gel'),
    image: img(() => require('../../assets/shop-packshots/la-roche-posay-effaclar.jpg')),
    blurb: 'A clear gel that rinses away shine without scrubbing at your skin.',
  },
  {
    id: 'krave-matcha-cleanser',
    brand: 'Krave Beauty',
    name: 'Matcha Hemp Hydrating Cleanser',
    step: 'cleanse',
    time: 'both',
    priceTier: 'mid',
    priceUsd: 18,
    concerns: ['dryness', 'sensitive', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Krave Beauty Matcha Hemp Hydrating Cleanser'),
    image: null,
    blurb: 'A low-foam green cleanser that leaves skin comfortable, not squeaky.',
  },
  {
    id: 'fresh-soy-cleanser',
    brand: 'Fresh',
    name: 'Soy Face Cleanser',
    step: 'cleanse',
    time: 'both',
    priceTier: 'premium',
    priceUsd: 42,
    concerns: ['sensitive', 'dryness', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Fresh Soy Face Cleanser'),
    image: null,
    blurb: 'A silky one-step wash that even takes light makeup off.',
  },
  {
    id: 'yttp-kale-cleanser',
    brand: 'Youth To The People',
    name: 'Superfood Antioxidant Cleanser',
    step: 'cleanse',
    time: 'both',
    priceTier: 'premium',
    priceUsd: 39,
    concerns: ['oil', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Youth To The People Superfood Cleanser'),
    image: null,
    blurb: 'A green-juice gel wash that cuts shine but skips the tight feeling.',
  },

  // ── TREAT ────────────────────────────────────────────────────────────────
  {
    id: 'paulas-choice-2-bha',
    brand: "Paula's Choice",
    name: 'Skin Perfecting 2% BHA Liquid',
    step: 'treat',
    time: 'PM',
    priceTier: 'mid',
    priceUsd: 35,
    concerns: ['breakouts', 'oil'],
    activeStrength: 'active',
    beginnerSafe: true,
    affiliateUrl: amazon("Paula's Choice 2% BHA Liquid"),
    image: img(() => require('../../assets/products/paulas-choice-2-bha.jpg')),
    blurb: 'A watery nightly step that keeps pores clear and calms bumpy patches.',
  },
  {
    id: 'to-niacinamide-10',
    brand: 'The Ordinary',
    name: 'Niacinamide 10% + Zinc 1%',
    step: 'treat',
    time: 'both',
    priceTier: 'budget',
    priceUsd: 6,
    concerns: ['oil', 'breakouts', 'dark_marks', 'redness'],
    activeStrength: 'gentle',
    beginnerSafe: true,
    affiliateUrl: amazon('The Ordinary Niacinamide 10% Zinc'),
    image: img(() => require('../../assets/shop-packshots/the-ordinary-niacinamide.png')),
    blurb: 'A simple serum that steadies shine and evens skin over weeks.',
  },
  {
    id: 'to-azelaic-10',
    brand: 'The Ordinary',
    name: 'Azelaic Acid Suspension 10%',
    step: 'treat',
    time: 'PM',
    priceTier: 'budget',
    priceUsd: 10,
    concerns: ['redness', 'dark_marks', 'breakouts'],
    activeStrength: 'gentle',
    beginnerSafe: true,
    affiliateUrl: amazon('The Ordinary Azelaic Acid Suspension 10%'),
    image: null,
    blurb: 'A cream that quiets red, uneven patches — gentle enough for most.',
  },
  {
    id: 'to-lactic-10',
    brand: 'The Ordinary',
    name: 'Lactic Acid 10% + HA',
    step: 'treat',
    time: 'PM',
    priceTier: 'budget',
    priceUsd: 9,
    concerns: ['dark_marks', 'dryness'],
    activeStrength: 'active',
    beginnerSafe: false,
    affiliateUrl: amazon('The Ordinary Lactic Acid 10% HA'),
    image: img(() => require('../../assets/products/the-ordinary-lactic-acid.jpg')),
    blurb: 'A nightly smoothing step that helps faded marks turn over faster.',
  },
  {
    id: 'to-retinal-02',
    brand: 'The Ordinary',
    name: 'Retinal 0.2% Emulsion',
    step: 'treat',
    time: 'PM',
    priceTier: 'budget',
    priceUsd: 14,
    concerns: ['dark_marks', 'breakouts'],
    activeStrength: 'active',
    beginnerSafe: false,
    affiliateUrl: amazon('The Ordinary Retinal 0.2% Emulsion'),
    image: img(() => require('../../assets/products/the-ordinary-retinal.jpg')),
    blurb: 'A stronger night step for marks and texture — build up slowly.',
  },
  {
    id: 'anua-heartleaf-77',
    brand: 'Anua',
    name: 'Heartleaf 77% Soothing Toner',
    step: 'treat',
    time: 'both',
    priceTier: 'mid',
    priceUsd: 18,
    concerns: ['redness', 'sensitive'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Anua Heartleaf 77 Soothing Toner'),
    image: img(() => require('../../assets/shop-packshots/anua-heartleaf.jpg')),
    blurb: 'A watery calming layer that takes the heat out of flushed skin.',
  },
  {
    id: 'lrp-cicaplast-b5',
    brand: 'La Roche-Posay',
    name: 'Cicaplast Baume B5+',
    step: 'treat',
    time: 'PM',
    priceTier: 'mid',
    priceUsd: 16,
    concerns: ['redness', 'dryness', 'sensitive'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('La Roche-Posay Cicaplast Baume B5'),
    image: null,
    blurb: 'A rich rescue balm for patches that feel rough or irritated.',
  },
  {
    id: 'inkey-hyaluronic',
    brand: 'The Inkey List',
    name: 'Hyaluronic Acid Serum',
    step: 'treat',
    time: 'both',
    priceTier: 'budget',
    priceUsd: 10,
    concerns: ['dryness'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('The Inkey List Hyaluronic Acid Serum'),
    image: null,
    blurb: 'A light water-pulling layer that makes tight skin feel cushioned.',
  },
  {
    id: 'vichy-mineral-89',
    brand: 'Vichy',
    name: 'Minéral 89 Daily Booster',
    step: 'treat',
    time: 'both',
    priceTier: 'mid',
    priceUsd: 30,
    concerns: ['dryness', 'sensitive'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Vichy Mineral 89 Booster'),
    image: null,
    blurb: 'A bouncy gel shot of hydration under anything else you use.',
  },
  {
    id: 'cosrx-snail-96',
    brand: 'COSRX',
    name: 'Advanced Snail 96 Mucin Essence',
    step: 'treat',
    time: 'both',
    priceTier: 'mid',
    priceUsd: 25,
    concerns: ['dryness', 'redness'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('COSRX Advanced Snail 96 Mucin Essence'),
    image: null,
    blurb: 'A cult favorite that leaves thirsty skin plump and settled.',
  },
  {
    id: 'naturium-vitc',
    brand: 'Naturium',
    name: 'Vitamin C Complex Serum',
    step: 'treat',
    time: 'AM',
    priceTier: 'mid',
    priceUsd: 20,
    concerns: ['dark_marks'],
    activeStrength: 'active',
    beginnerSafe: true,
    affiliateUrl: amazon('Naturium Vitamin C Complex Serum'),
    image: null,
    blurb: 'A morning brightener that helps old marks fade with daily use.',
  },
  {
    id: 'goodmolecules-discoloration',
    brand: 'Good Molecules',
    name: 'Discoloration Correcting Serum',
    step: 'treat',
    time: 'both',
    priceTier: 'budget',
    priceUsd: 12,
    concerns: ['dark_marks'],
    activeStrength: 'gentle',
    beginnerSafe: true,
    affiliateUrl: amazon('Good Molecules Discoloration Correcting Serum'),
    image: null,
    blurb: 'A quiet daily serum aimed squarely at leftover dark spots.',
  },
  {
    id: 'avene-cicalfate',
    brand: 'Avène',
    name: 'Cicalfate+ Restorative Cream',
    step: 'treat',
    time: 'PM',
    priceTier: 'mid',
    priceUsd: 28,
    concerns: ['redness', 'sensitive', 'dryness'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Avene Cicalfate+ Restorative Protective Cream'),
    image: null,
    blurb: 'A soothing cream for skin that acts up at the slightest thing.',
  },
  {
    id: 'pc-azelaic-booster',
    brand: "Paula's Choice",
    name: '10% Azelaic Acid Booster',
    step: 'treat',
    time: 'PM',
    priceTier: 'premium',
    priceUsd: 38,
    concerns: ['redness', 'dark_marks', 'breakouts'],
    activeStrength: 'gentle',
    beginnerSafe: true,
    affiliateUrl: amazon("Paula's Choice 10% Azelaic Acid Booster"),
    image: null,
    blurb: 'A cream-gel that works on redness and marks at the same time.',
  },

  // ── MOISTURIZE ───────────────────────────────────────────────────────────
  {
    id: 'kiehls-ultra-facial',
    brand: "Kiehl's",
    name: 'Ultra Facial Cream',
    step: 'moisturize',
    time: 'both',
    priceTier: 'premium',
    priceUsd: 38,
    concerns: ['dryness', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon("Kiehl's Ultra Facial Cream"),
    image: img(() => require('../../assets/products/kiehls-ultra-facial-cream.jpg')),
    blurb: 'A do-everything cream that keeps skin comfortable all day.',
  },
  {
    id: 'cerave-daily-lotion',
    brand: 'CeraVe',
    name: 'Daily Moisturizing Lotion',
    step: 'moisturize',
    time: 'both',
    priceTier: 'budget',
    priceUsd: 13,
    concerns: ['dryness', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('CeraVe Daily Moisturizing Lotion'),
    image: null,
    blurb: 'A light everyday lotion that sinks in fast and just works.',
  },
  {
    id: 'cerave-cream',
    brand: 'CeraVe',
    name: 'Moisturizing Cream',
    step: 'moisturize',
    time: 'PM',
    priceTier: 'budget',
    priceUsd: 17,
    concerns: ['dryness', 'sensitive'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('CeraVe Moisturizing Cream'),
    image: null,
    blurb: 'The thick tub classic for skin that drinks lotion and asks for more.',
  },
  {
    id: 'neutrogena-hydro-boost',
    brand: 'Neutrogena',
    name: 'Hydro Boost Water Gel',
    step: 'moisturize',
    time: 'both',
    priceTier: 'budget',
    priceUsd: 20,
    concerns: ['oil', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Neutrogena Hydro Boost Water Gel'),
    image: null,
    blurb: 'A cool water gel for skin that wants moisture without weight.',
  },
  {
    id: 'vanicream-daily-lotion',
    brand: 'Vanicream',
    name: 'Daily Facial Moisturizer',
    step: 'moisturize',
    time: 'both',
    priceTier: 'budget',
    priceUsd: 14,
    concerns: ['sensitive', 'redness', 'dryness'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Vanicream Daily Facial Moisturizer'),
    image: null,
    blurb: 'A plain, fragrance-free lotion reactive skin rarely argues with.',
  },
  {
    id: 'fab-ultra-repair',
    brand: 'First Aid Beauty',
    name: 'Ultra Repair Cream',
    step: 'moisturize',
    time: 'both',
    priceTier: 'mid',
    priceUsd: 38,
    concerns: ['dryness', 'sensitive', 'redness'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('First Aid Beauty Ultra Repair Cream'),
    image: null,
    blurb: 'A pillowy cream that calms rough, thirsty patches on contact.',
  },
  {
    id: 'lrp-toleriane-double-repair',
    brand: 'La Roche-Posay',
    name: 'Toleriane Double Repair Face Moisturizer',
    step: 'moisturize',
    time: 'both',
    priceTier: 'mid',
    priceUsd: 23,
    concerns: ['sensitive', 'redness', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('La Roche-Posay Toleriane Double Repair Moisturizer'),
    image: img(() => require('../../assets/products/la-roche-posay-toleriane-dd.jpg')),
    blurb: 'A steady daily moisturizer built for easily-annoyed skin.',
  },
  {
    id: 'belif-aqua-bomb',
    brand: 'belif',
    name: 'The True Cream Aqua Bomb',
    step: 'moisturize',
    time: 'both',
    priceTier: 'mid',
    priceUsd: 38,
    concerns: ['oil', 'dryness', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('belif The True Cream Aqua Bomb'),
    image: null,
    blurb: 'A whipped gel-cream that feels like nothing and hydrates like plenty.',
  },
  {
    id: 'tatcha-water-cream',
    brand: 'Tatcha',
    name: 'The Water Cream',
    step: 'moisturize',
    time: 'both',
    priceTier: 'premium',
    priceUsd: 70,
    concerns: ['oil', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Tatcha The Water Cream'),
    image: null,
    blurb: 'A featherweight luxury cream that leaves zero shine behind.',
  },

  // ── PROTECT (SPF — always in the routine, never skipped) ─────────────────
  {
    id: 'boj-relief-sun',
    brand: 'Beauty of Joseon',
    name: 'Relief Sun: Rice + Probiotics SPF50+',
    step: 'protect',
    time: 'AM',
    priceTier: 'budget',
    priceUsd: 18,
    concerns: ['all_skin', 'sensitive', 'dark_marks'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Beauty of Joseon Relief Sun SPF50'),
    image: img(() => require('../../assets/shop-packshots/beauty-of-joseon-relief-sun.jpg')),
    blurb: 'The sunscreen that feels like a light cream — you will actually wear it.',
  },
  {
    id: 'supergoop-unseen',
    brand: 'Supergoop!',
    name: 'Unseen Sunscreen SPF 40',
    step: 'protect',
    time: 'AM',
    priceTier: 'premium',
    priceUsd: 38,
    concerns: ['oil', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Supergoop Unseen Sunscreen SPF 40'),
    image: img(() => require('../../assets/products/supergoop-unseen.jpg')),
    blurb: 'An invisible gel sunscreen that doubles as a smooth makeup base.',
  },
  {
    id: 'eltamd-uv-clear',
    brand: 'EltaMD',
    name: 'UV Clear Broad-Spectrum SPF 46',
    step: 'protect',
    time: 'AM',
    priceTier: 'premium',
    priceUsd: 41,
    concerns: ['breakouts', 'redness', 'sensitive'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('EltaMD UV Clear SPF 46'),
    image: null,
    blurb: 'The derm-office favorite for skin that breaks out or flushes.',
  },
  {
    id: 'lrp-anthelios-milk',
    brand: 'La Roche-Posay',
    name: 'Anthelios Melt-in Milk SPF 60',
    step: 'protect',
    time: 'AM',
    priceTier: 'mid',
    priceUsd: 26,
    concerns: ['dryness', 'sensitive', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('La Roche-Posay Anthelios Melt-in Milk SPF 60'),
    image: null,
    blurb: 'A comfortable high-protection lotion that disappears into skin.',
  },
  {
    id: 'cerave-am-spf30',
    brand: 'CeraVe',
    name: 'AM Facial Moisturizing Lotion SPF 30',
    step: 'protect',
    time: 'AM',
    priceTier: 'budget',
    priceUsd: 17,
    concerns: ['all_skin', 'dryness'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('CeraVe AM Facial Moisturizing Lotion SPF 30'),
    image: null,
    blurb: 'Morning moisturizer and sun protection in one easy step.',
  },
  {
    id: 'neutrogena-ultra-sheer',
    brand: 'Neutrogena',
    name: 'Ultra Sheer Dry-Touch SPF 55',
    step: 'protect',
    time: 'AM',
    priceTier: 'budget',
    priceUsd: 12,
    concerns: ['oil', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Neutrogena Ultra Sheer Dry-Touch SPF 55'),
    image: null,
    blurb: 'The drugstore standby that dries down matte and stays put.',
  },
  {
    id: 'isntree-watery-sun',
    brand: 'Isntree',
    name: 'Hyaluronic Acid Watery Sun Gel SPF 50+',
    step: 'protect',
    time: 'AM',
    priceTier: 'budget',
    priceUsd: 16,
    concerns: ['dryness', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('Isntree Hyaluronic Acid Watery Sun Gel'),
    image: null,
    blurb: 'A juicy gel sunscreen that adds moisture instead of stealing it.',
  },
  {
    id: 'canmake-mermaid',
    brand: 'CANMAKE',
    name: 'Mermaid Skin Gel UV SPF 50+',
    step: 'protect',
    time: 'AM',
    priceTier: 'budget',
    priceUsd: 11,
    concerns: ['oil', 'all_skin'],
    activeStrength: 'none',
    beginnerSafe: true,
    affiliateUrl: amazon('CANMAKE Mermaid Skin Gel UV'),
    image: null,
    blurb: 'A tiny Japanese gel sunscreen people repurchase on autopilot.',
  },
];

/** Honest catalog audit used by the verifier: every step must offer at least
 *  one budget-tier SKU, or the "always offer a budget alternative" promise
 *  can't be kept. */
export function catalogBudgetCoverage(): Record<string, number> {
  const cover: Record<string, number> = {};
  for (const sku of COMMERCE_CATALOG) {
    if (sku.priceTier === 'budget') cover[sku.step] = (cover[sku.step] ?? 0) + 1;
  }
  return cover;
}
